// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOhRlSVOAe7WB6Ipt5AX7ukVcC9BbXBRY',
    appId: '1:847704492747:web:105d970489f3797402e94e',
    messagingSenderId: '847704492747',
    projectId: 'kpuapp-9dba6',
    authDomain: 'kpuapp-9dba6.firebaseapp.com',
    storageBucket: 'kpuapp-9dba6.appspot.com',
    measurementId: 'G-7GDPLGJBPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2cvKRsJ3a87P2dEStm7qgxrgnbGi0csc',
    appId: '1:847704492747:android:d26303ca24d8f00302e94e',
    messagingSenderId: '847704492747',
    projectId: 'kpuapp-9dba6',
    storageBucket: 'kpuapp-9dba6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS08mlw81EDFxsQ0ZPXPk33R-zCJUFwEI',
    appId: '1:847704492747:ios:d0aa5cc90637da0302e94e',
    messagingSenderId: '847704492747',
    projectId: 'kpuapp-9dba6',
    storageBucket: 'kpuapp-9dba6.appspot.com',
    iosBundleId: 'com.example.kpuAppSerkom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS08mlw81EDFxsQ0ZPXPk33R-zCJUFwEI',
    appId: '1:847704492747:ios:d0aa5cc90637da0302e94e',
    messagingSenderId: '847704492747',
    projectId: 'kpuapp-9dba6',
    storageBucket: 'kpuapp-9dba6.appspot.com',
    iosBundleId: 'com.example.kpuAppSerkom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOhRlSVOAe7WB6Ipt5AX7ukVcC9BbXBRY',
    appId: '1:847704492747:web:2a34dcfe6a53a82a02e94e',
    messagingSenderId: '847704492747',
    projectId: 'kpuapp-9dba6',
    authDomain: 'kpuapp-9dba6.firebaseapp.com',
    storageBucket: 'kpuapp-9dba6.appspot.com',
    measurementId: 'G-Y5Q1MD6CR6',
  );
}
